
import { Language, TeamMember, Device, ROM, TeamApplication } from './types';

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    nav_home: "Home",
    nav_features: "Features",
    nav_download: "Download",
    nav_team: "Team",
    nav_about: "About",
    // Home
    home_hero_title: "The OS that respects your",
    home_hero_title_animated: "rest.",
    home_hero_subtitle: "Experience Android like never before. Smooth, stable, and designed for you.",
    home_hero_cta_features: "View Features",
    home_hero_cta_download: "Download",
    home_rom_types: "Choose Your Flavor",
    home_rom_sleepos_desc: "Our flagship HyperOS-based experience, packed with features and optimizations.",
    home_rom_aosp_desc: "A clean, bloat-free AOSP experience for purists who crave performance.",
    home_rom_port_desc: "Enjoy features from other devices, ported with stability and care.",
    home_advantages_title: "Why Project Sleep?",
    home_advantage_1_title: "Peak Performance",
    home_advantage_1_desc: "Optimized for speed and battery life.",
    home_advantage_2_title: "Clean UI",
    home_advantage_2_desc: "A beautiful and intuitive interface.",
    home_advantage_3_title: "Community Driven",
    home_advantage_3_desc: "Developed with feedback from users like you.",
    home_advantage_4_title: "Regular Updates",
    home_advantage_4_desc: "Stay secure and up-to-date.",
    // Features
    features_title: "Core Features",
    features_subtitle: "Discover what makes each version unique.",
    features_tab_sleepos: "SleepOS",
    features_tab_aosp: "AOSP",
    features_tab_port: "Port ROMs",
    features_sleepos_desc: "Built on the rock-solid foundation of HyperOS, SleepOS enhances your experience with unique customizations, performance tweaks, and a focus on battery efficiency without sacrificing functionality.",
    features_aosp_desc: "For those who love the stock Android feel, our AOSP builds provide a clean, fast, and secure experience. We add only the most essential enhancements, keeping it close to Google's vision.",
    features_port_desc: "Experience the best features from other popular devices on yours. Our Port ROMs are carefully adapted to ensure stability and compatibility, giving you a fresh look and feel.",
    // Download
    download_title: "Find Your Build",
    download_subtitle: "Select your device to see available ROMs.",
    download_search_placeholder: "Search by brand, model, or codename...",
    download_filter_all: "All",
    download_no_roms: "No ROMs found for this device yet. Stay tuned!",
    download_recommended: "Recommended",
    download_version: "Version",
    download_android_version: "Android",
    download_file_size: "Size",
    download_changelog: "Changelog",
    download_notes: "Notes",
    download_button: "Download",
    // Team
    team_title: "Our Team",
    team_subtitle: "The passionate developers behind Project Sleep.",
    team_join_title: "Join The Team",
    team_join_subtitle: "We're always looking for talented individuals. Apply now!",
    team_form_name: "Full Name",
    team_form_email: "Email Address",
    team_form_role: "Desired Role (e.g., Developer, Maintainer)",
    team_form_country: "Country (2-letter code, e.g., US)",
    team_form_experience: "Tell us about your experience",
    team_form_submit: "Submit Application",
    team_form_success: "Application submitted! We will get back to you soon.",
    // About
    about_title: "About Project Sleep",
    about_subtitle: "Our mission, vision, and community.",
    about_p1: "Project Sleep was born from a simple idea: to create a custom Android experience that is stable, feature-rich, and beautiful, without the bloat. We believe in open-source and community-driven development.",
    about_p2: "Our team is a global collective of developers, designers, and enthusiasts dedicated to pushing the boundaries of what's possible on Android devices. Join us on our journey.",
    about_connect: "Connect With Us",
    about_telegram_channel: "Telegram Channel",
    about_telegram_group: "Telegram Group",
    about_discord: "Discord",
    about_github: "GitHub",
  },
  id: {
    nav_home: "Beranda",
    nav_features: "Fitur",
    nav_download: "Unduh",
    nav_team: "Tim",
    nav_about: "Tentang",
    home_hero_title: "OS yang menghargai",
    home_hero_title_animated: "istirahat Anda.",
    home_hero_subtitle: "Rasakan Android yang belum pernah ada sebelumnya. Lancar, stabil, dan dirancang untuk Anda.",
    home_hero_cta_features: "Lihat Fitur",
    home_hero_cta_download: "Unduh",
    home_rom_types: "Pilih Versi Anda",
    home_rom_sleepos_desc: "Pengalaman andalan kami berbasis HyperOS, penuh dengan fitur dan optimisasi.",
    home_rom_aosp_desc: "Pengalaman AOSP yang bersih dan bebas bloatware untuk para puritan yang menginginkan performa.",
    home_rom_port_desc: "Nikmati fitur dari perangkat lain, di-porting dengan stabilitas dan perhatian.",
    home_advantages_title: "Mengapa Project Sleep?",
    home_advantage_1_title: "Performa Puncak",
    home_advantage_1_desc: "Dioptimalkan untuk kecepatan dan daya tahan baterai.",
    home_advantage_2_title: "UI Bersih",
    home_advantage_2_desc: "Antarmuka yang indah dan intuitif.",
    home_advantage_3_title: "Digerakkan Komunitas",
    home_advantage_3_desc: "Dikembangkan dengan masukan dari pengguna seperti Anda.",
    home_advantage_4_title: "Pembaruan Rutin",
    home_advantage_4_desc: "Tetap aman dan terkini.",
    features_title: "Fitur Inti",
    features_subtitle: "Temukan apa yang membuat setiap versi unik.",
    features_tab_sleepos: "SleepOS",
    features_tab_aosp: "AOSP",
    features_tab_port: "Port ROM",
    features_sleepos_desc: "Dibangun di atas fondasi HyperOS yang kokoh, SleepOS menyempurnakan pengalaman Anda dengan kustomisasi unik, penyesuaian performa, dan fokus pada efisiensi baterai tanpa mengorbankan fungsionalitas.",
    features_aosp_desc: "Bagi mereka yang menyukai nuansa stok Android, build AOSP kami memberikan pengalaman yang bersih, cepat, dan aman. Kami hanya menambahkan peningkatan paling esensial, menjaganya tetap dekat dengan visi Google.",
    features_port_desc: "Rasakan fitur terbaik dari perangkat populer lainnya di perangkat Anda. Port ROM kami diadaptasi dengan cermat untuk memastikan stabilitas dan kompatibilitas, memberi Anda tampilan dan nuansa baru.",
    download_title: "Temukan Build Anda",
    download_subtitle: "Pilih perangkat Anda untuk melihat ROM yang tersedia.",
    download_search_placeholder: "Cari berdasarkan merek, model, atau nama kode...",
    download_filter_all: "Semua",
    download_no_roms: "Belum ada ROM yang ditemukan untuk perangkat ini. Nantikan!",
    download_recommended: "Direkomendasikan",
    download_version: "Versi",
    download_android_version: "Android",
    download_file_size: "Ukuran",
    download_changelog: "Log Perubahan",
    download_notes: "Catatan",
    download_button: "Unduh",
    team_title: "Tim Kami",
    team_subtitle: "Para pengembang bersemangat di balik Project Sleep.",
    team_join_title: "Gabung dengan Tim",
    team_join_subtitle: "Kami selalu mencari individu berbakat. Daftar sekarang!",
    team_form_name: "Nama Lengkap",
    team_form_email: "Alamat Email",
    team_form_role: "Peran yang Diinginkan (mis., Pengembang, Maintainer)",
    team_form_country: "Negara (kode 2 huruf, mis., ID)",
    team_form_experience: "Ceritakan tentang pengalaman Anda",
    team_form_submit: "Kirim Lamaran",
    team_form_success: "Lamaran terkirim! Kami akan segera menghubungi Anda.",
    about_title: "Tentang Project Sleep",
    about_subtitle: "Misi, visi, dan komunitas kami.",
    about_p1: "Project Sleep lahir dari ide sederhana: menciptakan pengalaman Android kustom yang stabil, kaya fitur, dan indah, tanpa bloatware. Kami percaya pada pengembangan sumber terbuka dan berbasis komunitas.",
    about_p2: "Tim kami adalah kolektif global pengembang, desainer, dan penggemar yang berdedikasi untuk mendorong batas-batas dari apa yang mungkin di perangkat Android. Bergabunglah dengan kami dalam perjalanan kami.",
    about_connect: "Terhubung Dengan Kami",
    about_telegram_channel: "Channel Telegram",
    about_telegram_group: "Grup Telegram",
    about_discord: "Discord",
    about_github: "GitHub",
  },
  hi: {
    nav_home: "होम",
    nav_features: "विशेषताएँ",
    nav_download: "डाउनलोड",
    nav_team: "टीम",
    nav_about: "हमारे बारे में",
    home_hero_title: "ओएस जो आपके",
    home_hero_title_animated: "आराम का सम्मान करता है।",
    home_hero_subtitle: "एंड्रॉयड का ऐसा अनुभव जो पहले कभी नहीं हुआ। स्मूथ, स्थिर, और आपके लिए डिज़ाइन किया गया।",
    home_hero_cta_features: "विशेषताएँ देखें",
    home_hero_cta_download: "डाउनलोड करें",
    home_rom_types: "अपना फ्लेवर चुनें",
    home_rom_sleepos_desc: "हमारा प्रमुख HyperOS-आधारित अनुभव, सुविधाओं और अनुकूलन से भरपूर।",
    home_rom_aosp_desc: "प्रदर्शन चाहने वाले शुद्धतावादियों के लिए एक स्वच्छ, ब्लोट-मुक्त AOSP अनुभव।",
    home_rom_port_desc: "स्थिरता और देखभाल के साथ पोर्ट किए गए अन्य उपकरणों की सुविधाओं का आनंद लें।",
    home_advantages_title: "Project Sleep क्यों?",
    home_advantage_1_title: "उच्चतम प्रदर्शन",
    home_advantage_1_desc: "गति और बैटरी जीवन के लिए अनुकूलित।",
    home_advantage_2_title: "स्वच्छ यूआई",
    home_advantage_2_desc: "एक सुंदर और सहज इंटरफ़ेस।",
    home_advantage_3_title: "समुदाय द्वारा संचालित",
    home_advantage_3_desc: "आप जैसे उपयोगकर्ताओं की प्रतिक्रिया से विकसित।",
    home_advantage_4_title: "नियमित अपडेट",
    home_advantage_4_desc: "सुरक्षित और अद्यतित रहें।",
    features_title: "मुख्य विशेषताएँ",
    features_subtitle: "जानें कि प्रत्येक संस्करण को क्या अद्वितीय बनाता है।",
    features_tab_sleepos: "SleepOS",
    features_tab_aosp: "AOSP",
    features_tab_port: "पोर्ट रोम",
    features_sleepos_desc: "HyperOS की ठोस नींव पर निर्मित, SleepOS अद्वितीय अनुकूलन, प्रदर्शन ट्वीक और कार्यक्षमता का त्याग किए बिना बैटरी दक्षता पर ध्यान केंद्रित करके आपके अनुभव को बढ़ाता है।",
    features_aosp_desc: "जो लोग स्टॉक एंड्रॉइड अनुभव पसंद करते हैं, उनके लिए हमारे AOSP बिल्ड एक स्वच्छ, तेज़ और सुरक्षित अनुभव प्रदान करते हैं। हम केवल सबसे आवश्यक संवर्द्धन जोड़ते हैं, इसे Google के दृष्टिकोण के करीब रखते हुए।",
    features_port_desc: "अन्य लोकप्रिय उपकरणों की सर्वोत्तम सुविधाओं का अनुभव अपने डिवाइस पर करें। हमारे पोर्ट रोम स्थिरता और संगतता सुनिश्चित करने के लिए सावधानीपूर्वक अनुकूलित किए गए हैं, जो आपको एक नया रूप और अनुभव देते हैं।",
    download_title: "अपना बिल्ड खोजें",
    download_subtitle: "उपलब्ध रोम देखने के लिए अपना डिवाइस चुनें।",
    download_search_placeholder: "ब्रांड, मॉडल या कोडनेम द्वारा खोजें...",
    download_filter_all: "सभी",
    download_no_roms: "इस डिवाइस के लिए अभी तक कोई रोम नहीं मिला। बने रहें!",
    download_recommended: "अनुशंसित",
    download_version: "संस्करण",
    download_android_version: "एंड्रॉयड",
    download_file_size: "आकार",
    download_changelog: "चेंजलॉग",
    download_notes: "नोट्स",
    download_button: "डाउनलोड करें",
    team_title: "हमारी टीम",
    team_subtitle: "Project Sleep के पीछे के उत्साही डेवलपर्स।",
    team_join_title: "टीम में शामिल हों",
    team_join_subtitle: "हम हमेशा प्रतिभाशाली व्यक्तियों की तलाश में रहते हैं। अभी आवेदन करें!",
    team_form_name: "पूरा नाम",
    team_form_email: "ईमेल पता",
    team_form_role: "वांछित भूमिका (जैसे, डेवलपर, मेंटेनर)",
    team_form_country: "देश (2-अक्षर का कोड, जैसे, IN)",
    team_form_experience: "हमें अपने अनुभव के बारे में बताएं",
    team_form_submit: "आवेदन जमा करें",
    team_form_success: "आवेदन जमा हो गया! हम जल्द ही आपसे संपर्क करेंगे।",
    about_title: "Project Sleep के बारे में",
    about_subtitle: "हमारा मिशन, दृष्टिकोण और समुदाय।",
    about_p1: "Project Sleep एक साधारण विचार से पैदा हुआ था: एक कस्टम एंड्रॉइड अनुभव बनाने के लिए जो स्थिर, सुविधा संपन्न और सुंदर हो, बिना ब्लोट के। हम ओपन-सोर्स और समुदाय-संचालित विकास में विश्वास करते हैं।",
    about_p2: "हमारी टीम डेवलपर्स, डिजाइनरों और उत्साही लोगों का एक वैश्विक समूह है जो एंड्रॉइड उपकरणों पर जो संभव है उसकी सीमाओं को आगे बढ़ाने के लिए समर्पित है। हमारी यात्रा में शामिल हों।",
    about_connect: "हमसे जुड़ें",
    about_telegram_channel: "टेलीग्राम चैनल",
    about_telegram_group: "टेलीग्राम समूह",
    about_discord: "डिस्कॉर्ड",
    about_github: "गिटहब",
  },
  ta: {
    nav_home: "முகப்பு",
    nav_features: "அம்சங்கள்",
    nav_download: "பதிவிறக்கம்",
    nav_team: "குழு",
    nav_about: "பற்றி",
    home_hero_title: "உங்கள் ஓய்வை மதிக்கும்",
    home_hero_title_animated: "ஓஎஸ்.",
    home_hero_subtitle: "முன்னெப்போதும் இல்லாத வகையில் ஆண்ட்ராய்டை அனுபவியுங்கள். மென்மையான, நிலையான மற்றும் உங்களுக்காக வடிவமைக்கப்பட்டது.",
    home_hero_cta_features: "அம்சங்களைக் காண்க",
    home_hero_cta_download: "பதிவிறக்கு",
    home_rom_types: "உங்கள் சுவையைத் தேர்ந்தெடுங்கள்",
    home_rom_sleepos_desc: "எங்கள் முதன்மை HyperOS-அடிப்படையிலான அனுபவம், அம்சங்கள் மற்றும் மேம்படுத்தல்களுடன் நிரம்பியுள்ளது.",
    home_rom_aosp_desc: "செயல்திறனை விரும்பும் தூய்மைவாதிகளுக்கு ஒரு சுத்தமான, வீக்கமில்லாத AOSP அனுபவம்.",
    home_rom_port_desc: "மற்ற சாதனங்களின் அம்சங்களை நிலைத்தன்மை மற்றும் கவனத்துடன் போர்ட் செய்து மகிழுங்கள்.",
    home_advantages_title: "ஏன் Project Sleep?",
    home_advantage_1_title: "உச்ச செயல்திறன்",
    home_advantage_1_desc: "வேகம் மற்றும் பேட்டரி ஆயுள் కోసం மேம்படுத்தப்பட்டது.",
    home_advantage_2_title: "சுத்தமான இடைமுகம்",
    home_advantage_2_desc: "ஒரு அழகான மற்றும் உள்ளுணர்வு இடைமுகம்.",
    home_advantage_3_title: "சமூகத்தால் இயக்கப்படுகிறது",
    home_advantage_3_desc: "உங்களைப் போன்ற பயனர்களின் பின்னூட்டத்துடன் உருவாக்கப்பட்டது.",
    home_advantage_4_title: "வழக்கமான புதுப்பிப்புகள்",
    home_advantage_4_desc: "பாதுப்பாகவும் புதுப்பித்த நிலையில் இருங்கள்.",
    features_title: "முக்கிய அம்சங்கள்",
    features_subtitle: "ஒவ்வொரு பதிப்பையும் தனித்துவமாக்குவது எது என்பதைக் கண்டறியவும்.",
    features_tab_sleepos: "SleepOS",
    features_tab_aosp: "AOSP",
    features_tab_port: "போர்ட் ரோம்",
    features_sleepos_desc: "HyperOS இன் உறுதியான அடித்தளத்தில் கட்டமைக்கப்பட்ட, SleepOS உங்கள் அனுபவத்தை தனித்துவமான தனிப்பயனாக்கல்கள், செயல்திறன் மாற்றங்கள் மற்றும் செயல்பாட்டை தியாகம் செய்யாமல் பேட்டரி செயல்திறனில் கவனம் செலுத்துகிறது.",
    features_aosp_desc: "ஸ்டாக் ஆண்ட்ராய்டு உணர்வை விரும்புவோருக்கு, எங்கள் AOSP உருவாக்கங்கள் சுத்தமான, வேகமான மற்றும் பாதுகாப்பான அனுபவத்தை வழங்குகின்றன. கூகிளின் பார்வைக்கு நெருக்கமாக வைத்து, மிக அவசியமான மேம்பாடுகளை மட்டுமே நாங்கள் சேர்க்கிறோம்.",
    features_port_desc: "மற்ற பிரபலமான சாதனங்களின் சிறந்த அம்சங்களை உங்களுடையதில் அனுபவிக்கவும். எங்கள் போர்ட் ரோம்கள் நிலைத்தன்மை மற்றும் பொருந்தக்கூடிய தன்மையை உறுதி செய்வதற்காக கவனமாக மாற்றியமைக்கப்பட்டுள்ளன, இது உங்களுக்கு ஒரு புதிய தோற்றத்தையும் உணர்வையும் அளிக்கிறது.",
    download_title: "உங்கள் உருவாக்கத்தைக் கண்டறியவும்",
    download_subtitle: "கிடைக்கக்கூடிய ரோம்களைக் காண உங்கள் சாதனத்தைத் தேர்ந்தெடுக்கவும்.",
    download_search_placeholder: "பிராண்ட், மாடல் அல்லது குறியீட்டுப்பெயர் மூலம் தேடவும்...",
    download_filter_all: "அனைத்தும்",
    download_no_roms: "இந்தச் சாதனத்திற்கு இன்னும் ரோம் எதுவும் கிடைக்கவில்லை. காத்திருங்கள்!",
    download_recommended: "பரிந்துரைக்கப்பட்டது",
    download_version: "பதிப்பு",
    download_android_version: "ஆண்ட்ராய்டு",
    download_file_size: "அளவு",
    download_changelog: "மாற்றங்கள்",
    download_notes: "குறிப்புகள்",
    download_button: "பதிவிறக்கு",
    team_title: "எங்கள் குழு",
    team_subtitle: "Project Sleep க்குப் பின்னால் உள்ள ஆர்வமுள்ள டெவலப்பர்கள்.",
    team_join_title: "குழுவில் சேரவும்",
    team_join_subtitle: "நாங்கள் எப்போதும் திறமையான நபர்களைத் தேடுகிறோம். இப்போது விண்ணப்பிக்கவும்!",
    team_form_name: "முழு பெயர்",
    team_form_email: "மின்னஞ்சல் முகவரி",
    team_form_role: "விரும்பிய பங்கு (எ.கா., டெவலப்பர், பராமரிப்பாளர்)",
    team_form_country: "நாடு (2-எழுத்து குறியீடு, எ.கா., IN)",
    team_form_experience: "உங்கள் அனுபவத்தைப் பற்றி எங்களிடம் கூறுங்கள்",
    team_form_submit: "விண்ணப்பத்தை சமர்ப்பிக்கவும்",
    team_form_success: "விண்ணப்பம் சமர்ப்பிக்கப்பட்டது! நாங்கள் விரைவில் உங்களைத் தொடர்புகொள்வோம்.",
    about_title: "Project Sleep பற்றி",
    about_subtitle: "எங்கள் நோக்கம், பார்வை மற்றும் சமூகம்.",
    about_p1: "Project Sleep ஒரு எளிய யோசனையிலிருந்து பிறந்தது: வீக்கம் இல்லாமல் நிலையான, அம்சம் நிறைந்த மற்றும் அழகான ஒரு தனிப்பயன் ஆண்ட்ராய்டு அனுபவத்தை உருவாக்குவது. நாங்கள் திறந்த மூல மற்றும் சமூகம் சார்ந்த வளர்ச்சியில் நம்பிக்கை கொண்டுள்ளோம்.",
    about_p2: "எங்கள் குழு டெவலப்பர்கள், வடிவமைப்பாளர்கள் மற்றும் ஆர்வலர்களின் உலகளாவிய கூட்டமைப்பாகும், இது ஆண்ட்ராய்டு சாதனங்களில் சாத்தியமானவற்றின் எல்லைகளைத் தள்ள அர்ப்பணிக்கப்பட்டுள்ளது. எங்கள் பயணத்தில் எங்களுடன் சேரவும்.",
    about_connect: "எங்களுடன் இணையுங்கள்",
    about_telegram_channel: "டெலிகிராம் சேனல்",
    about_telegram_group: "டெலிகிராம் குழு",
    about_discord: "டிஸ்கார்ட்",
    about_github: "கிட்ஹப்",
  },
  ru: {
    nav_home: "Главная",
    nav_features: "Особенности",
    nav_download: "Скачать",
    nav_team: "Команда",
    nav_about: "О проекте",
    home_hero_title: "ОС, которая уважает ваш",
    home_hero_title_animated: "отдых.",
    home_hero_subtitle: "Испытайте Android, как никогда раньше. Плавный, стабильный и созданный для вас.",
    home_hero_cta_features: "Посмотреть особенности",
    home_hero_cta_download: "Скачать",
    home_rom_types: "Выберите свой вариант",
    home_rom_sleepos_desc: "Наш флагманский опыт на базе HyperOS, наполненный функциями и оптимизациями.",
    home_rom_aosp_desc: "Чистый AOSP без лишнего для ценителей производительности.",
    home_rom_port_desc: "Наслаждайтесь функциями с других устройств, портированными со стабильностью и заботой.",
    home_advantages_title: "Почему Project Sleep?",
    home_advantage_1_title: "Пиковая производительность",
    home_advantage_1_desc: "Оптимизировано для скорости и времени работы от батареи.",
    home_advantage_2_title: "Чистый интерфейс",
    home_advantage_2_desc: "Красивый и интуитивно понятный интерфейс.",
    home_advantage_3_title: "Развивается сообществом",
    home_advantage_3_desc: "Разработано с учетом отзывов пользователей, таких как вы.",
    home_advantage_4_title: "Регулярные обновления",
    home_advantage_4_desc: "Оставайтесь в безопасности и с последними обновлениями.",
    features_title: "Ключевые особенности",
    features_subtitle: "Узнайте, что делает каждую версию уникальной.",
    features_tab_sleepos: "SleepOS",
    features_tab_aosp: "AOSP",
    features_tab_port: "Портированные ROM",
    features_sleepos_desc: "Созданный на прочной основе HyperOS, SleepOS улучшает ваш опыт уникальными настройками, улучшениями производительности и акцентом на энергоэффективность без ущерба для функциональности.",
    features_aosp_desc: "Для тех, кто любит ощущение стокового Android, наши сборки AOSP обеспечивают чистый, быстрый и безопасный опыт. Мы добавляем только самые необходимые улучшения, сохраняя его близким к видению Google.",
    features_port_desc: "Испытайте лучшие функции с других популярных устройств на своем. Наши портированные ROM тщательно адаптированы для обеспечения стабильности и совместимости, придавая вам свежий вид и ощущения.",
    download_title: "Найдите свою сборку",
    download_subtitle: "Выберите ваше устройство, чтобы увидеть доступные прошивки.",
    download_search_placeholder: "Поиск по бренду, модели или кодовому названию...",
    download_filter_all: "Все",
    download_no_roms: "Для этого устройства пока нет прошивок. Следите за обновлениями!",
    download_recommended: "Рекомендуется",
    download_version: "Версия",
    download_android_version: "Android",
    download_file_size: "Размер",
    download_changelog: "Список изменений",
    download_notes: "Примечания",
    download_button: "Скачать",
    team_title: "Наша команда",
    team_subtitle: "Увлеченные разработчики, стоящие за Project Sleep.",
    team_join_title: "Присоединиться к команде",
    team_join_subtitle: "Мы всегда ищем талантливых людей. Подайте заявку сейчас!",
    team_form_name: "Полное имя",
    team_form_email: "Электронная почта",
    team_form_role: "Желаемая роль (например, Разработчик, Сопровождающий)",
    team_form_country: "Страна (2-буквенный код, например, RU)",
    team_form_experience: "Расскажите нам о своем опыте",
    team_form_submit: "Отправить заявку",
    team_form_success: "Заявка отправлена! Мы скоро с вами свяжемся.",
    about_title: "О Project Sleep",
    about_subtitle: "Наша миссия, видение и сообщество.",
    about_p1: "Project Sleep родился из простой идеи: создать кастомный Android, который будет стабильным, многофункциональным и красивым, без лишнего. Мы верим в открытый исходный код и разработку, управляемую сообществом.",
    about_p2: "Наша команда — это глобальное сообщество разработчиков, дизайнеров и энтузиастов, посвященных расширению границ возможного на устройствах Android. Присоединяйтесь к нашему путешествию.",
    about_connect: "Свяжитесь с нами",
    about_telegram_channel: "Канал в Telegram",
    about_telegram_group: "Группа в Telegram",
    about_discord: "Discord",
    about_github: "GitHub",
  },
  th: {
    nav_home: "หน้าแรก",
    nav_features: "ฟีเจอร์",
    nav_download: "ดาวน์โหลด",
    nav_team: "ทีม",
    nav_about: "เกี่ยวกับ",
    home_hero_title: "ระบบปฏิบัติการที่เคารพ",
    home_hero_title_animated: "การพักผ่อนของคุณ",
    home_hero_subtitle: "สัมผัสประสบการณ์ Android อย่างที่ไม่เคยมีมาก่อน ราบรื่น เสถียร และออกแบบมาเพื่อคุณ",
    home_hero_cta_features: "ดูฟีเจอร์",
    home_hero_cta_download: "ดาวน์โหลด",
    home_rom_types: "เลือกรสชาติของคุณ",
    home_rom_sleepos_desc: "ประสบการณ์หลักของเราที่ใช้ HyperOS ซึ่งเต็มไปด้วยฟีเจอร์และการปรับแต่ง",
    home_rom_aosp_desc: "ประสบการณ์ AOSP ที่สะอาดปราศจากโบลต์แวร์สำหรับผู้ที่ต้องการประสิทธิภาพสูงสุด",
    home_rom_port_desc: "เพลิดเพลินกับฟีเจอร์จากอุปกรณ์อื่น ๆ ที่พอร์ตมาพร้อมกับความเสถียรและความเอาใจใส่",
    home_advantages_title: "ทำไมต้อง Project Sleep?",
    home_advantage_1_title: "ประสิทธิภาพสูงสุด",
    home_advantage_1_desc: "ปรับให้เหมาะสมสำหรับความเร็วและอายุการใช้งานแบตเตอรี่",
    home_advantage_2_title: "UI ที่สะอาด",
    home_advantage_2_desc: "อินเทอร์เฟซที่สวยงามและใช้งานง่าย",
    home_advantage_3_title: "ขับเคลื่อนโดยชุมชน",
    home_advantage_3_desc: "พัฒนาโดยรับฟังความคิดเห็นจากผู้ใช้เช่นคุณ",
    home_advantage_4_title: "อัปเดตสม่ำเสมอ",
    home_advantage_4_desc: "ปลอดภัยและทันสมัยอยู่เสมอ",
    features_title: "ฟีเจอร์หลัก",
    features_subtitle: "ค้นพบสิ่งที่ทำให้แต่ละเวอร์ชันมีเอกลักษณ์",
    features_tab_sleepos: "SleepOS",
    features_tab_aosp: "AOSP",
    features_tab_port: "พอร์ต ROM",
    features_sleepos_desc: "สร้างขึ้นบนรากฐานที่มั่นคงของ HyperOS, SleepOS ช่วยเพิ่มประสบการณ์ของคุณด้วยการปรับแต่งที่ไม่เหมือนใคร การปรับแต่งประสิทธิภาพ และการเน้นประสิทธิภาพของแบตเตอรี่โดยไม่ลดทอนฟังก์ชันการทำงาน",
    features_aosp_desc: "สำหรับผู้ที่ชื่นชอบความรู้สึกของ Android แบบดั้งเดิม บิวด์ AOSP ของเรามอบประสบการณ์ที่สะอาด รวดเร็ว และปลอดภัย เราเพิ่มเฉพาะการปรับปรุงที่จำเป็นที่สุดเท่านั้น เพื่อให้ใกล้เคียงกับวิสัยทัศน์ของ Google",
    features_port_desc: "สัมผัสประสบการณ์ฟีเจอร์ที่ดีที่สุดจากอุปกรณ์ยอดนิยมอื่น ๆ บนอุปกรณ์ของคุณ พอร์ต ROM ของเราได้รับการปรับแต่งอย่างรอบคอบเพื่อให้มั่นใจถึงความเสถียรและความเข้ากันได้ ทำให้คุณได้รูปลักษณ์และความรู้สึกที่สดใหม่",
    download_title: "ค้นหาบิวด์ของคุณ",
    download_subtitle: "เลือกอุปกรณ์ของคุณเพื่อดู ROM ที่มีอยู่",
    download_search_placeholder: "ค้นหาตามแบรนด์ รุ่น หรือโค้ดเนม...",
    download_filter_all: "ทั้งหมด",
    download_no_roms: "ยังไม่พบ ROM สำหรับอุปกรณ์นี้ คอยติดตาม!",
    download_recommended: "แนะนำ",
    download_version: "เวอร์ชัน",
    download_android_version: "Android",
    download_file_size: "ขนาด",
    download_changelog: "บันทึกการเปลี่ยนแปลง",
    download_notes: "หมายเหตุ",
    download_button: "ดาวน์โหลด",
    team_title: "ทีมของเรา",
    team_subtitle: "นักพัฒนาผู้หลงใหลเบื้องหลัง Project Sleep",
    team_join_title: "เข้าร่วมทีม",
    team_join_subtitle: "เรามองหาผู้ที่มีความสามารถอยู่เสมอ สมัครเลย!",
    team_form_name: "ชื่อเต็ม",
    team_form_email: "ที่อยู่อีเมล",
    team_form_role: "ตำแหน่งที่ต้องการ (เช่น นักพัฒนา, ผู้ดูแล)",
    team_form_country: "ประเทศ (รหัส 2 ตัวอักษร เช่น TH)",
    team_form_experience: "บอกเราเกี่ยวกับประสบการณ์ของคุณ",
    team_form_submit: "ส่งใบสมัคร",
    team_form_success: "ส่งใบสมัครแล้ว! เราจะติดต่อกลับไปเร็ว ๆ นี้",
    about_title: "เกี่ยวกับ Project Sleep",
    about_subtitle: "ภารกิจ วิสัยทัศน์ และชุมชนของเรา",
    about_p1: "Project Sleep เกิดจากแนวคิดง่ายๆ: เพื่อสร้างประสบการณ์ Android ที่กำหนดเองซึ่งมีเสถียรภาพ มีฟีเจอร์มากมาย และสวยงาม โดยไม่มีโบลต์แวร์ เราเชื่อมั่นในการพัฒนาแบบโอเพนซอร์สและขับเคลื่อนโดยชุมชน",
    about_p2: "ทีมของเราคือนักพัฒนา นักออกแบบ และผู้ที่ชื่นชอบจากทั่วโลกที่อุทิศตนเพื่อผลักดันขีดจำกัดของสิ่งที่เป็นไปได้บนอุปกรณ์ Android มาร่วมเดินทางกับเรา",
    about_connect: "เชื่อมต่อกับเรา",
    about_telegram_channel: "ช่อง Telegram",
    about_telegram_group: "กลุ่ม Telegram",
    about_discord: "Discord",
    about_github: "GitHub",
  },
  vi: {
    nav_home: "Trang chủ",
    nav_features: "Tính năng",
    nav_download: "Tải xuống",
    nav_team: "Đội ngũ",
    nav_about: "Giới thiệu",
    home_hero_title: "Hệ điều hành tôn trọng",
    home_hero_title_animated: "sự nghỉ ngơi của bạn.",
    home_hero_subtitle: "Trải nghiệm Android chưa từng có. Mượt mà, ổn định và được thiết kế cho bạn.",
    home_hero_cta_features: "Xem tính năng",
    home_hero_cta_download: "Tải xuống",
    home_rom_types: "Chọn hương vị của bạn",
    home_rom_sleepos_desc: "Trải nghiệm hàng đầu dựa trên HyperOS của chúng tôi, tích hợp nhiều tính năng và tối ưu hóa.",
    home_rom_aosp_desc: "Trải nghiệm AOSP sạch sẽ, không có bloatware cho những người theo chủ nghĩa thuần túy khao khát hiệu suất.",
    home_rom_port_desc: "Tận hưởng các tính năng từ các thiết bị khác, được chuyển đổi với sự ổn định và cẩn thận.",
    home_advantages_title: "Tại sao chọn Project Sleep?",
    home_advantage_1_title: "Hiệu suất đỉnh cao",
    home_advantage_1_desc: "Tối ưu hóa cho tốc độ và thời lượng pin.",
    home_advantage_2_title: "Giao diện người dùng sạch",
    home_advantage_2_desc: "Giao diện đẹp và trực quan.",
    home_advantage_3_title: "Do cộng đồng định hướng",
    home_advantage_3_desc: "Được phát triển với phản hồi từ những người dùng như bạn.",
    home_advantage_4_title: "Cập nhật thường xuyên",
    home_advantage_4_desc: "Luôn an toàn và cập nhật.",
    features_title: "Các tính năng cốt lõi",
    features_subtitle: "Khám phá điều gì làm cho mỗi phiên bản trở nên độc đáo.",
    features_tab_sleepos: "SleepOS",
    features_tab_aosp: "AOSP",
    features_tab_port: "ROM Port",
    features_sleepos_desc: "Được xây dựng trên nền tảng vững chắc của HyperOS, SleepOS nâng cao trải nghiệm của bạn với các tùy chỉnh độc đáo, tinh chỉnh hiệu suất và tập trung vào hiệu quả pin mà không làm giảm chức năng.",
    features_aosp_desc: "Đối với những người yêu thích cảm giác Android gốc, các bản dựng AOSP của chúng tôi cung cấp trải nghiệm sạch sẽ, nhanh chóng và an toàn. Chúng tôi chỉ thêm những cải tiến cần thiết nhất, giữ cho nó gần với tầm nhìn của Google.",
    features_port_desc: "Trải nghiệm các tính năng tốt nhất từ các thiết bị phổ biến khác trên thiết bị của bạn. Các ROM Port của chúng tôi được điều chỉnh cẩn thận để đảm bảo sự ổn định và tương thích, mang đến cho bạn một giao diện và cảm nhận mới mẻ.",
    download_title: "Tìm bản dựng của bạn",
    download_subtitle: "Chọn thiết bị của bạn để xem các ROM có sẵn.",
    download_search_placeholder: "Tìm kiếm theo thương hiệu, kiểu máy hoặc tên mã...",
    download_filter_all: "Tất cả",
    download_no_roms: "Chưa tìm thấy ROM nào cho thiết bị này. Hãy theo dõi!",
    download_recommended: "Đề xuất",
    download_version: "Phiên bản",
    download_android_version: "Android",
    download_file_size: "Kích thước",
    download_changelog: "Nhật ký thay đổi",
    download_notes: "Ghi chú",
    download_button: "Tải xuống",
    team_title: "Đội ngũ của chúng tôi",
    team_subtitle: "Các nhà phát triển đầy nhiệt huyết đằng sau Project Sleep.",
    team_join_title: "Gia nhập đội ngũ",
    team_join_subtitle: "Chúng tôi luôn tìm kiếm những cá nhân tài năng. Ứng tuyển ngay!",
    team_form_name: "Họ và tên",
    team_form_email: "Địa chỉ email",
    team_form_role: "Vai trò mong muốn (ví dụ: Nhà phát triển, Người bảo trì)",
    team_form_country: "Quốc gia (mã 2 chữ cái, ví dụ: VN)",
    team_form_experience: "Hãy cho chúng tôi biết về kinh nghiệm của bạn",
    team_form_submit: "Gửi đơn ứng tuyển",
    team_form_success: "Đã gửi đơn ứng tuyển! Chúng tôi sẽ sớm liên hệ lại với bạn.",
    about_title: "Giới thiệu Project Sleep",
    about_subtitle: "Sứ mệnh, tầm nhìn và cộng đồng của chúng tôi.",
    about_p1: "Project Sleep ra đời từ một ý tưởng đơn giản: tạo ra một trải nghiệm Android tùy chỉnh ổn định, giàu tính năng và đẹp mắt, không có bloatware. Chúng tôi tin vào sự phát triển mã nguồn mở và do cộng đồng định hướng.",
    about_p2: "Đội ngũ của chúng tôi là một tập thể toàn cầu gồm các nhà phát triển, nhà thiết kế và những người đam mê cống hiến để vượt qua ranh giới của những gì có thể trên các thiết bị Android. Hãy tham gia hành trình của chúng tôi.",
    about_connect: "Kết nối với chúng tôi",
    about_telegram_channel: "Kênh Telegram",
    about_telegram_group: "Nhóm Telegram",
    about_discord: "Discord",
    about_github: "GitHub",
  },
  ar: {
    nav_home: "الرئيسية",
    nav_features: "الميزات",
    nav_download: "التنزيل",
    nav_team: "الفريق",
    nav_about: "حول",
    home_hero_title: "نظام التشغيل الذي يحترم",
    home_hero_title_animated: "راحتك.",
    home_hero_subtitle: "جرب أندرويد كما لم يحدث من قبل. سلس ومستقر ومصمم من أجلك.",
    home_hero_cta_features: "عرض الميزات",
    home_hero_cta_download: "تنزيل",
    home_rom_types: "اختر نكهتك",
    home_rom_sleepos_desc: "تجربتنا الرائدة القائمة على HyperOS، المليئة بالميزات والتحسينات.",
    home_rom_aosp_desc: "تجربة AOSP نظيفة وخالية من البرامج غير المرغوب فيها للمتحمسين الذين يتوقون إلى الأداء.",
    home_rom_port_desc: "استمتع بميزات من الأجهزة الأخرى، تم نقلها بثبات وعناية.",
    home_advantages_title: "لماذا Project Sleep؟",
    home_advantage_1_title: "أداء فائق",
    home_advantage_1_desc: "محسن للسرعة وعمر البطارية.",
    home_advantage_2_title: "واجهة مستخدم نظيفة",
    home_advantage_2_desc: "واجهة جميلة وبديهية.",
    home_advantage_3_title: "يقوده المجتمع",
    home_advantage_3_desc: "تم تطويره بملاحظات من مستخدمين مثلك.",
    home_advantage_4_title: "تحديثات منتظمة",
    home_advantage_4_desc: "ابق آمنًا ومحدثًا.",
    features_title: "الميزات الأساسية",
    features_subtitle: "اكتشف ما يجعل كل إصدار فريدًا.",
    features_tab_sleepos: "SleepOS",
    features_tab_aosp: "AOSP",
    features_tab_port: "رومات منقولة",
    features_sleepos_desc: "بني على أساس HyperOS المتين، يعزز SleepOS تجربتك بتخصيصات فريدة وتعديلات في الأداء وتركيز على كفاءة البطارية دون التضحية بالوظائف.",
    features_aosp_desc: "لأولئك الذين يحبون إحساس أندرويد الخام، توفر إصدارات AOSP الخاصة بنا تجربة نظيفة وسريعة وآمنة. نضيف فقط التحسينات الأكثر أهمية، مع إبقائها قريبة من رؤية جوجل.",
    features_port_desc: "جرب أفضل الميزات من الأجهزة الشائعة الأخرى على جهازك. تم تكييف روماتنا المنقولة بعناية لضمان الاستقرار والتوافق، مما يمنحك مظهرًا وإحساسًا جديدًا.",
    download_title: "ابحث عن إصدارك",
    download_subtitle: "حدد جهازك لرؤية الرومات المتاحة.",
    download_search_placeholder: "ابحث حسب العلامة التجارية أو الطراز أو الاسم الرمزي...",
    download_filter_all: "الكل",
    download_no_roms: "لم يتم العثور على رومات لهذا الجهاز بعد. ترقبوا!",
    download_recommended: "موصى به",
    download_version: "الإصدار",
    download_android_version: "أندرويد",
    download_file_size: "الحجم",
    download_changelog: "سجل التغييرات",
    download_notes: "ملاحظات",
    download_button: "تنزيل",
    team_title: "فريقنا",
    team_subtitle: "المطورون الشغوفون وراء Project Sleep.",
    team_join_title: "انضم إلى الفريق",
    team_join_subtitle: "نبحث دائمًا عن أفراد موهوبين. قدم الآن!",
    team_form_name: "الاسم الكامل",
    team_form_email: "البريد الإلكتروني",
    team_form_role: "الدور المطلوب (مثل مطور، مشرف)",
    team_form_country: "البلد (رمز من حرفين، مثل SA)",
    team_form_experience: "أخبرنا عن خبرتك",
    team_form_submit: "إرسال الطلب",
    team_form_success: "تم إرسال الطلب! سنتواصل معك قريبًا.",
    about_title: "حول Project Sleep",
    about_subtitle: "مهمتنا ورؤيتنا ومجتمعنا.",
    about_p1: "ولد Project Sleep من فكرة بسيطة: إنشاء تجربة أندرويد مخصصة مستقرة وغنية بالميزات وجميلة، بدون برامج غير مرغوب فيها. نؤمن بالتطوير مفتوح المصدر والمجتمعي.",
    about_p2: "فريقنا عبارة عن مجموعة عالمية من المطورين والمصممين والمتحمسين المكرسين لدفع حدود ما هو ممكن على أجهزة أندرويد. انضم إلينا في رحلتنا.",
    about_connect: "تواصل معنا",
    about_telegram_channel: "قناة تيليجرام",
    about_telegram_group: "مجموعة تيليجرام",
    about_discord: "ديسكورد",
    about_github: "جيت هاب",
  },
  ka: {
    nav_home: "მთავარი",
    nav_features: "მახასიათებლები",
    nav_download: "გადმოწერა",
    nav_team: "გუნდი",
    nav_about: "შესახებ",
    home_hero_title: "ოპერაციული სისტემა, რომელიც პატივს სცემს",
    home_hero_title_animated: "თქვენს დასვენებას.",
    home_hero_subtitle: "განიცადეთ ანდროიდი, როგორც არასდროს. გლუვი, სტაბილური და თქვენთვის შექმნილი.",
    home_hero_cta_features: "მახასიათებლების ნახვა",
    home_hero_cta_download: "გადმოწერა",
    home_rom_types: "აირჩიეთ თქვენი ვერსია",
    home_rom_sleepos_desc: "ჩვენი ფლაგმანი HyperOS-ზე დაფუძნებული გამოცდილება, სავსე ფუნქციებითა და ოპტიმიზაციებით.",
    home_rom_aosp_desc: "სუფთა, ზედმეტი პროგრამებისგან თავისუფალი AOSP გამოცდილება პერფექციონისტებისთვის, რომლებსაც სურთ წარმადობა.",
    home_rom_port_desc: "ისიამოვნეთ სხვა მოწყობილობების ფუნქციებით, რომლებიც პორტირებულია სტაბილურობითა და ზრუნვით.",
    home_advantages_title: "რატომ Project Sleep?",
    home_advantage_1_title: "უმაღლესი წარმადობა",
    home_advantage_1_desc: "ოპტიმიზირებულია სიჩქარისა და ბატარეის ხანგრძლივობისთვის.",
    home_advantage_2_title: "სუფთა ინტერფეისი",
    home_advantage_2_desc: "ლამაზი და ინტუიციური ინტერფეისი.",
    home_advantage_3_title: "საზოგადოებაზე ორიენტირებული",
    home_advantage_3_desc: "შემუშავებულია თქვენნაირი მომხმარებლების გამოხმაურებით.",
    home_advantage_4_title: "რეგულარული განახლებები",
    home_advantage_4_desc: "იყავით დაცული და განახლებული.",
    features_title: "ძირითადი მახასიათებლები",
    features_subtitle: "აღმოაჩინეთ, რა ხდის თითოეულ ვერსიას უნიკალურს.",
    features_tab_sleepos: "SleepOS",
    features_tab_aosp: "AOSP",
    features_tab_port: "პორტირებული რომები",
    features_sleepos_desc: "აშენებული HyperOS-ის მყარ საფუძველზე, SleepOS აუმჯობესებს თქვენს გამოცდილებას უნიკალური პერსონალიზაციით, წარმადობის გაუმჯობესებით და ბატარეის ეფექტურობაზე ფოკუსირებით ფუნქციონალურობის შეწირვის გარეშე.",
    features_aosp_desc: "მათთვის, ვისაც უყვარს სუფთა ანდროიდის შეგრძნება, ჩვენი AOSP ბილდები გთავაზობთ სუფთა, სწრაფ და უსაფრთხო გამოცდილებას. ჩვენ ვამატებთ მხოლოდ ყველაზე აუცილებელ გაუმჯობესებებს, რაც მას Google-ის ხედვასთან ახლოს ინარჩუნებს.",
    features_port_desc: "განიცადეთ საუკეთესო ფუნქციები სხვა პოპულარული მოწყობილობებიდან თქვენს მოწყობილობაზე. ჩვენი პორტირებული რომები საგულდაგულოდ არის ადაპტირებული სტაბილურობისა და თავსებადობის უზრუნველსაყოფად, რაც გაძლევთ ახალ იერსახესა და შეგრძნებას.",
    download_title: "იპოვეთ თქვენი ბილდი",
    download_subtitle: "აირჩიეთ თქვენი მოწყობილობა ხელმისაწვდომი რომების სანახავად.",
    download_search_placeholder: "ძიება ბრენდის, მოდელის ან კოდური სახელის მიხედვით...",
    download_filter_all: "ყველა",
    download_no_roms: "ამ მოწყობილობისთვის რომები ჯერ არ მოიძებნა. თვალყური ადევნეთ!",
    download_recommended: "რეკომენდებული",
    download_version: "ვერსია",
    download_android_version: "ანდროიდი",
    download_file_size: "ზომა",
    download_changelog: "ცვლილებების ისტორია",
    download_notes: "შენიშვნები",
    download_button: "გადმოწერა",
    team_title: "ჩვენი გუნდი",
    team_subtitle: "ენთუზიასტი დეველოპერები Project Sleep-ის უკან.",
    team_join_title: "შემოუერთდით გუნდს",
    team_join_subtitle: "ჩვენ ყოველთვის ვეძებთ ნიჭიერ ადამიანებს. შემოგვიერთდით ახლავე!",
    team_form_name: "სრული სახელი",
    team_form_email: "ელ. ფოსტა",
    team_form_role: "სასურველი როლი (მაგ., დეველოპერი, მეინთეინერი)",
    team_form_country: "ქვეყანა (2-ასოიანი კოდი, მაგ., GE)",
    team_form_experience: "მოგვიყევით თქვენი გამოცდილების შესახებ",
    team_form_submit: "განაცხადის გაგზავნა",
    team_form_success: "განაცხადი გაგზავნილია! ჩვენ მალე დაგიკავშირდებით.",
    about_title: "Project Sleep-ის შესახებ",
    about_subtitle: "ჩვენი მისია, ხედვა და საზოგადოება.",
    about_p1: "Project Sleep დაიბადა მარტივი იდეიდან: შეგვექმნა მორგებული ანდროიდის გამოცდილება, რომელიც არის სტაბილური, ფუნქციებით მდიდარი და ლამაზი, ზედმეტი პროგრამების გარეშე. ჩვენ გვჯერა ღია კოდისა და საზოგადოების მიერ მართული განვითარების.",
    about_p2: "ჩვენი გუნდი არის დეველოპერების, დიზაინერებისა და ენთუზიასტების გლობალური კოლექტივი, რომელიც ეძღვნება ანდროიდის მოწყობილობებზე შესაძლებლობების საზღვრების გაფართოებას. შემოგვიერთდით ჩვენს მოგზაურობაში.",
    about_connect: "დაგვიკავშირდით",
    about_telegram_channel: "ტელეგრამის არხი",
    about_telegram_group: "ტელეგრამის ჯგუფი",
    about_discord: "დისქორდი",
    about_github: "გიტჰაბი",
  },
};


export const seedData = {
  team: [
    { id: '1', name: 'Adi Setiawan', role: 'Founder & Lead Developer', country: 'ID', avatar: 'https://i.pravatar.cc/150?u=adi', socials: { github: '#', telegram: '#' } },
    { id: '2', name: 'Jane Doe', role: 'UI/UX Designer', country: 'US', avatar: 'https://i.pravatar.cc/150?u=jane', socials: { twitter: '#'} },
    { id: '3', name: 'Ivan Petrov', role: 'AOSP Developer', country: 'RU', avatar: 'https://i.pravatar.cc/150?u=ivan', socials: { github: '#'} },
    { id: '4', name: 'Priya Sharma', role: 'Device Maintainer', country: 'IN', avatar: 'https://i.pravatar.cc/150?u=priya', socials: { telegram: '#' } },
  ] as TeamMember[],
  devices: [
    { id: 'dev-1', brand: 'Xiaomi', model: 'Redmi Note 10 Pro', codename: 'sweet', chipset: 'Snapdragon 732G', imageUrl: 'https://picsum.photos/seed/sweet/400/300' },
    { id: 'dev-2', brand: 'Poco', model: 'X3 Pro', codename: 'vayu', chipset: 'Snapdragon 860', imageUrl: 'https://picsum.photos/seed/vayu/400/300' },
    { id: 'dev-3', brand: 'OnePlus', model: '9 Pro', codename: 'lemonadep', chipset: 'Snapdragon 888', imageUrl: 'https://picsum.photos/seed/lemonadep/400/300' },
    { id: 'dev-4', brand: 'Google', model: 'Pixel 6', codename: 'oriole', chipset: 'Tensor', imageUrl: 'https://picsum.photos/seed/oriole/400/300' },
  ] as Device[],
  roms: [
    { id: 'rom-1', deviceId: 'dev-1', type: 'SleepOS', version: '2.5', androidVersion: '14', fileSize: '2.2 GB', changelog: 'Initial stable release. Based on HyperOS. Improved battery life.', notes: 'Clean flash recommended.', isRecommended: true, downloadUrl: '#', releaseDate: '2024-07-15' },
    { id: 'rom-2', deviceId: 'dev-1', type: 'AOSP', version: '14.0', androidVersion: '14', fileSize: '1.8 GB', changelog: 'Pure AOSP experience. Latest security patch.', notes: 'GApps not included.', isRecommended: false, downloadUrl: '#', releaseDate: '2024-07-10' },
    { id: 'rom-3', deviceId: 'dev-2', type: 'SleepOS', version: '2.5', androidVersion: '14', fileSize: '2.3 GB', changelog: 'Initial stable release. Gaming performance tweaks.', notes: 'Use recommended recovery.', isRecommended: true, downloadUrl: '#', releaseDate: '2024-07-20' },
    { id: 'rom-4', deviceId: 'dev-3', type: 'Port', version: 'OxygenOS 15 Port', androidVersion: '14', fileSize: '2.5 GB', changelog: 'Ported from OnePlus 12. All core features working.', notes: 'Some minor bugs may exist.', isRecommended: false, downloadUrl: '#', releaseDate: '2024-07-18' },
  ] as ROM[],
  applications: [
      { id: 'app-1', name: 'John Smith', email: 'john@test.com', role: 'Maintainer for "bacon"', country: 'CA', experience: '5 years experience with AOSP.', status: 'pending' }
  ] as TeamApplication[]
};
